#!/usr/bin/env bash
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$root"

errors=0

fail() {
    printf 'boundary error: %s\n' "$1" >&2
    errors=$((errors + 1))
}

required_files=(
    .editorconfig
    .gitattributes
    .gitignore
    CHANGELOG.md
    CODE_OF_CONDUCT.md
    CONTRIBUTING.md
    LICENSE
    Makefile
    NOTICE
    README.md
    SECURITY.md
    incan.lock
    incan.toml
    src/lib.incn
    src/package_loader.incn
    src/runtime.incn
    tests/test_package_loader_contract.incn
    tests/test_runtime_contract.incn
    workspaces/docs-site/mkdocs.yml
)

for path in "${required_files[@]}"; do
    if [[ ! -f "$path" ]]; then
        fail "required file is missing: $path"
    fi
done

for path in src/*.incn; do
    case "$path" in
        src/lib.incn | src/package_loader.incn | src/runtime.incn) ;;
        *) fail "source module is outside the public allowlist: $path" ;;
    esac
done

allowed_docs=(
    workspaces/docs-site/docs/architecture.md
    workspaces/docs-site/docs/contracts.md
    workspaces/docs-site/docs/development.md
    workspaces/docs-site/docs/getting-started.md
    workspaces/docs-site/docs/index.md
)

while IFS= read -r path; do
    allowed=false
    for expected in "${allowed_docs[@]}"; do
        if [[ "$path" == "$expected" ]]; then
            allowed=true
        fi
    done
    if [[ "$allowed" != true ]]; then
        fail "documentation file is outside the canonical docs allowlist: $path"
    fi
done < <(find workspaces/docs-site/docs -type f -print | sort)

while IFS= read -r path; do
    case "$path" in
        ./.git/* | ./target/* | */target/* | */site/*) continue ;;
        */.agents/* | */outputs/* | */reference/* | */research/* | */corpora/* | */models/*)
            fail "private or generated path is present: ${path#./}"
            ;;
        *.mjs | *.js | *.pdf | *.pptx | *.docx | *.gguf | *.safetensors | *.onnx | *.zip | *.tar | *.tar.gz)
            fail "disallowed artifact type is present: ${path#./}"
            ;;
    esac
done < <(find . -type f -print | sort)

while IFS= read -r path; do
    case "$path" in
        ./.git/* | ./target/* | */target/* | */site/*) continue ;;
        *) fail "symbolic links are not allowed in the publication candidate: ${path#./}" ;;
    esac
done < <(find . -type l -print | sort)

if rg -n --hidden \
    --glob '!.git/**' \
    --glob '!target/**' \
    --glob '!**/target/**' \
    --glob '!**/site/**' \
    --glob '!tools/validation/check_framework_boundary.sh' \
    '(/Users/|/home/[^/[:space:]]+/|[A-Za-z]:[\\/]+Users[\\/])' .; then
    fail "absolute personal filesystem path found"
fi

if rg -n --hidden \
    --glob '!.git/**' \
    --glob '!target/**' \
    --glob '!**/target/**' \
    --glob '!**/site/**' \
    --glob '!tools/validation/check_framework_boundary.sh' \
    '(-----BEGIN [A-Z ]*PRIVATE KEY-----|AKIA[0-9A-Z]{16}|gh[pousr]_[A-Za-z0-9_]{20,}|sk-[A-Za-z0-9]{20,})' .; then
    fail "high-confidence credential pattern found"
fi

if rg -n --hidden \
    --glob '!.git/**' \
    --glob '!target/**' \
    --glob '!**/target/**' \
    --glob '!**/site/**' \
    '@(gmail|outlook|hotmail)\.' .; then
    fail "personal email address found"
fi

if ! rg -q '^license = "Apache-2.0"$' incan.toml; then
    fail "incan.toml must use the Apache-2.0 SPDX identifier"
fi

if ! rg -q '^incan-version = "0.4.0"$' incan.lock; then
    fail "incan.lock must be generated by released Incan 0.4.0"
fi

if [[ "$errors" -ne 0 ]]; then
    printf 'framework boundary failed with %d error(s)\n' "$errors" >&2
    exit 1
fi

printf 'framework boundary passed\n'
